const APP = { houses: [], settings: { activeHouses: {}, theme: 'light' }, entries: [], db: null, marketOutcomes: 2, legCount: 2 };
const NAV = [
  ['dashboard','⌂','Início','Visão geral'],['surebet','%','Surebet','Calculadora de surebet'],['spins','↻','Giros','Giros grátis'],['houses','◈','Casas','Minhas casas'],['history','≡','Histórico','Histórico'],['reports','▤','Relatórios','Relatórios']
];
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
const brl = n => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n)||0);
const pct = n => `${(Number(n)||0).toFixed(2).replace('.',',')}%`;
const todayISO = () => new Date().toISOString().slice(0,10);
const uid = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
const parseNum = v => Number(String(v??'').replace(',','.')) || 0;
const esc = s => String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));

function toast(msg){ const t=$('#toast'); t.textContent=msg; t.classList.add('show'); clearTimeout(t._to); t._to=setTimeout(()=>t.classList.remove('show'),2200); }
function moneyClass(n){ return n>0?'positive':n<0?'negative':''; }

function openDB(){ return new Promise((resolve,reject)=>{ const req=indexedDB.open('SureControlDB',1); req.onupgradeneeded=e=>{ const db=e.target.result; if(!db.objectStoreNames.contains('entries')) db.createObjectStore('entries',{keyPath:'id'}); if(!db.objectStoreNames.contains('settings')) db.createObjectStore('settings',{keyPath:'key'}); }; req.onsuccess=()=>{APP.db=req.result;resolve()}; req.onerror=()=>reject(req.error); }); }
function dbGetAll(store){return new Promise((res,rej)=>{const r=APP.db.transaction(store,'readonly').objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function dbPut(store,obj){return new Promise((res,rej)=>{const r=APP.db.transaction(store,'readwrite').objectStore(store).put(obj);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function dbDelete(store,id){return new Promise((res,rej)=>{const r=APP.db.transaction(store,'readwrite').objectStore(store).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function loadData(){ APP.entries=await dbGetAll('entries'); const settings=await dbGetAll('settings'); const s=settings.find(x=>x.key==='appSettings'); if(s) APP.settings={activeHouses:{},theme:'light',...s.value}; }
async function saveSettings(){ await dbPut('settings',{key:'appSettings',value:APP.settings}); }
async function addEntry(entry){ APP.entries.push(entry); await dbPut('entries',entry); renderAll(); }
async function removeEntry(id){ APP.entries=APP.entries.filter(e=>e.id!==id); await dbDelete('entries',id); renderAll(); toast('Registro excluído.'); }

function applyTheme(theme,save=false){const next=theme==='dark'?'dark':'light';document.documentElement.setAttribute('data-theme',next);document.body?.setAttribute('data-theme',next);APP.settings.theme=next;try{localStorage.setItem('surecontrol-theme',next)}catch{}const btn=$('#themeToggle'),meta=document.querySelector('meta[name="theme-color"]');if(btn){const ico=btn.querySelector('.theme-icon');if(ico)ico.textContent=next==='dark'?'☀':'☾';btn.title=next==='dark'?'Usar modo claro':'Usar modo noturno';btn.setAttribute('aria-label',btn.title);btn.setAttribute('aria-pressed',next==='dark'?'true':'false')}if(meta)meta.content=next==='dark'?'#080f1b':'#f5f8ff';if(save&&APP.db)saveSettings();try{drawChart()}catch{}}
function toggleTheme(){applyTheme((APP.settings.theme||'light')==='dark'?'light':'dark',true)}
function renderNav(){ const html=NAV.map(([id,ico,label])=>`<button class="nav-btn ${id==='dashboard'?'active':''}" data-nav="${id}"><span class="nav-ico">${ico}</span><span>${label}</span></button>`).join(''); $('#desktopNav').innerHTML=html; $('#mobileNav').innerHTML=html; }
function navigate(id){ $$('.view').forEach(v=>v.classList.remove('active')); $(`#view-${id}`).classList.add('active'); $$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.nav===id)); $('#pageTitle').textContent=NAV.find(x=>x[0]===id)?.[3]||'SureControl'; window.scrollTo({top:0,behavior:'smooth'}); }

function entryProfit(e){ return parseNum(e.profit); }
function dateOnly(s){ return new Date(`${s}T12:00:00`); }
function sums(){ const now=new Date(); now.setHours(23,59,59,999); const today=todayISO(); const weekStart=new Date(now); weekStart.setDate(now.getDate()-6); weekStart.setHours(0,0,0,0); const monthStart=new Date(now.getFullYear(),now.getMonth(),1); let res={today:0,week:0,month:0,total:0,todayCount:0}; for(const e of APP.entries){ const p=entryProfit(e), d=dateOnly(e.date); res.total+=p; if(e.date===today){res.today+=p;res.todayCount++} if(d>=weekStart&&d<=now)res.week+=p; if(d>=monthStart&&d<=now)res.month+=p; } return res; }
function setMoney(id,val){ const el=$(id); el.textContent=brl(val); el.className=moneyClass(val); }
function renderDashboard(){ const s=sums(); setMoney('#sumToday',s.today);setMoney('#sumWeek',s.week);setMoney('#sumMonth',s.month);setMoney('#sumTotal',s.total); $('#sumTodayCount').textContent=`${s.todayCount} ${s.todayCount===1?'registro':'registros'}`; $('#monthLabel').textContent=new Intl.DateTimeFormat('pt-BR',{month:'long'}).format(new Date()); renderBalances(); renderRecent(); drawChart(); }
function activeHouses(){ return Object.entries(APP.settings.activeHouses||{}).filter(([,v])=>v.active); }
function houseById(id){return APP.houses.find(h=>h.id===id)}
function houseLogo(h){if(h?.temLogo&&h.logo)return `<img class="house-logo" src="${esc(h.logo)}" onerror="this.outerHTML='<span class=\'house-logo logo-fallback\'>${esc((h.nome||'?').slice(0,2))}</span>'">`; return `<span class="house-logo logo-fallback">${esc((h?.nome||'?').slice(0,2))}</span>`;}
function renderBalances(){ const arr=activeHouses().sort((a,b)=>(b[1].balance||0)-(a[1].balance||0)); const box=$('#balanceList'); if(!arr.length){box.className='balance-list empty-state';box.textContent='Nenhuma casa configurada.';} else { box.className='balance-list'; box.innerHTML=arr.slice(0,7).map(([id,v])=>{const h=houseById(id);return `<div class="balance-row"><div class="house-id">${houseLogo(h)}<div><b>${esc(h?.nome||id)}</b><small>${esc(h?.dominio||'')}</small></div></div><strong>${brl(v.balance)}</strong></div>`}).join(''); } $('#bankTotal').textContent=brl(arr.reduce((a,[,v])=>a+parseNum(v.balance),0)); }
function entryLabel(e){return e.type==='surebet'?(e.event||'Surebet'):e.type==='spins'?`Giros grátis • ${houseById(e.house)?.nome||e.house||'Casa'}`:(e.description||'Ajuste manual')}
function renderRecent(){ const arr=[...APP.entries].sort((a,b)=>(b.date+b.createdAt).localeCompare(a.date+a.createdAt)).slice(0,6), box=$('#recentList'); if(!arr.length){box.className='activity-list empty-state';box.textContent='Ainda não há movimentações.';return} box.className='activity-list';box.innerHTML=arr.map(e=>`<div class="activity"><div><b>${esc(entryLabel(e))}</b><small>${new Date(e.date+'T12:00:00').toLocaleDateString('pt-BR')} • ${e.type==='surebet'?'Surebet':e.type==='spins'?'Giros grátis':'Manual'}</small></div><strong class="${moneyClass(entryProfit(e))}">${brl(entryProfit(e))}</strong></div>`).join(''); }

function dailySeries(days){ const map={}; APP.entries.forEach(e=>map[e.date]=(map[e.date]||0)+entryProfit(e)); const labels=[], vals=[]; let acc=0; for(let i=days-1;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const iso=d.toISOString().slice(0,10);acc+=map[iso]||0;labels.push(`${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}`);vals.push(acc)} return {labels,vals}; }
function drawChart(){ const c=$('#profitChart'),ctx=c.getContext('2d'),days=parseInt($('#chartRange').value); const d=dailySeries(days),W=c.clientWidth*devicePixelRatio,H=220*devicePixelRatio;c.width=W;c.height=H;ctx.scale(devicePixelRatio,devicePixelRatio);const w=c.clientWidth,h=220,pad=28;ctx.clearRect(0,0,w,h);const min=Math.min(0,...d.vals),max=Math.max(0,...d.vals),span=(max-min)||1;ctx.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--line').trim()||'#dbe5f2';ctx.lineWidth=1;for(let i=0;i<4;i++){const y=pad+(h-pad*2)*(i/3);ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(w-pad,y);ctx.stroke()} const pts=d.vals.map((v,i)=>[pad+(w-pad*2)*(i/Math.max(1,d.vals.length-1)),h-pad-((v-min)/span)*(h-pad*2)]); if(pts.length){ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--blue').trim()||'#2563eb';ctx.lineWidth=2.4;ctx.stroke();ctx.lineTo(pts.at(-1)[0],h-pad);ctx.lineTo(pts[0][0],h-pad);ctx.closePath();const g=ctx.createLinearGradient(0,pad,0,h-pad);g.addColorStop(0,document.documentElement.dataset.theme==='dark'?'rgba(96,165,250,.22)':'rgba(37,99,235,.18)');g.addColorStop(1,'rgba(37,99,235,0)');ctx.fillStyle=g;ctx.fill()} ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--muted').trim()||'#64748b';ctx.font='10px system-ui';[0,Math.floor((days-1)/2),days-1].forEach(i=>{if(d.labels[i])ctx.fillText(d.labels[i],pad+(w-pad*2)*(i/Math.max(1,days-1))-12,h-6)}); }

function readLegRows(){return [...$$('.outcome-row')].map((r,i)=>({house:r.querySelector('.out-house')?.value||'',odd:r.querySelector('.out-odd')?.value||'',stake:r.querySelector('.out-stake')?.value||'100',betType:r.dataset.betType||'back',commissionEnabled:r.querySelector('.out-commission-enabled')?.checked||false,commission:r.querySelector('.out-commission')?.value||'',boostEnabled:r.querySelector('.out-boost-enabled')?.checked||false,boost:r.querySelector('.out-boost')?.value||'',freebet:r.querySelector('.out-freebet')?.checked||false,fixed:r.classList.contains('stake-fixed')||i===0}));}
function renderOutcomeRows(){
  const existing=APP._restoreLegs||readLegRows();
  APP.marketOutcomes=APP.legCount;
  $('#outcomeRows').innerHTML=Array.from({length:APP.legCount},(_,i)=>{const e=existing[i]||{};const fixed=e.fixed!==undefined?e.fixed:i===0;const betType=e.betType==='lay'?'lay':'back';const commissionEnabled=!!e.commissionEnabled||parseNum(e.commission)>0;const boostEnabled=!!e.boostEnabled||parseNum(e.boost)>0;return `<div class="outcome-row simple-sure-card ${fixed?'stake-fixed':''}" data-outcome-index="${i}" data-bet-type="${betType}">
    <div class="simple-card-head"><strong>Casa ${i+1}</strong><span class="result-badge">Resultado ${i+1}</span></div>
    <label class="out-house-wrap">Casa de aposta<select class="out-house">${houseOptions(e.house)}</select></label>
    <label>Odd<input class="out-odd" type="number" step="0.01" min="1.01" placeholder="2,10" value="${esc(e.odd||'')}"></label>
    <div class="odd-final-line"><span>Odd final</span><strong class="effective-odd">0,00</strong></div>
    <label>Stake<div class="stake-line"><div class="money-input"><span>R$</span><input class="out-stake" type="number" min="0" step="0.01" value="${esc(e.stake||'100')}"></div><button class="bet-toggle ${betType}" type="button" aria-label="Alternar Back e Lay">${betType==='lay'?'L':'B'}</button></div><small class="lay-liability"></small></label>
    <div class="option-list">
      <label class="option-toggle"><input class="out-commission-enabled" type="checkbox" ${commissionEnabled?'checked':''}><span>Comissão</span></label>
      <div class="inline-percent commission-percent ${commissionEnabled?'show':''}"><input class="out-commission" type="number" min="0" max="100" step="0.01" value="${esc(e.commission||'')}"><span>%</span></div>
      <label class="option-toggle"><input class="out-freebet" type="checkbox" ${e.freebet?'checked':''}><span>Freebet</span></label>
      <label class="option-toggle"><input class="out-boost-enabled" type="checkbox" ${boostEnabled?'checked':''}><span>Aumento</span></label>
      <div class="inline-percent boost-percent ${boostEnabled?'show':''}"><input class="out-boost" type="number" min="0" step="0.01" value="${esc(e.boost||'')}"><span>%</span></div>
    </div>
    <button type="button" class="fix-stake-btn ${fixed?'active':''}">${fixed?'Stake fixa':'Fixar stake'}</button>
  </div>`;}).join('');
  $$('.house-count-btn').forEach(b=>b.classList.toggle('active',+b.dataset.houseCount===APP.legCount));
  $$('.outcome-row').forEach(updateOutcomeRowUI);
}
function setHouseCount(n){n=Math.max(2,Math.min(6,+n||2));const rows=readLegRows();APP.legCount=n;APP.marketOutcomes=n;while(rows.length<n)rows.push({stake:'100',betType:'back',fixed:false});rows.length=n;if(!rows.some(r=>r.fixed)&&rows.length)rows[0].fixed=true;renderOutcomeRowsFrom(rows);resetSureDisplay();}
function addHouseLeg(){setHouseCount(APP.legCount+1)}
function removeHouseLeg(){setHouseCount(APP.legCount-1)}
function renderOutcomeRowsFrom(rows){$('#outcomeRows').innerHTML='';APP._restoreLegs=rows;renderOutcomeRows();delete APP._restoreLegs;}
function houseOptions(selected=''){ const active=activeHouses().map(([id])=>houseById(id)).filter(Boolean); const list=active.length?active:APP.houses; return `<option value="">Selecione</option>`+list.map(h=>`<option value="${esc(h.id)}" ${h.id===selected?'selected':''}>${esc(h.nome)}</option>`).join(''); }
function toggleBetType(row){const next=row.dataset.betType==='lay'?'back':'lay';if(next==='lay'&&row.querySelector('.out-freebet')?.checked){row.querySelector('.out-freebet').checked=false;toast('Freebet foi desmarcada porque aposta Lay não usa freebet.');}row.dataset.betType=next;updateOutcomeRowUI(row);resetSureDisplay();}
function setFixedRow(row){$$('.outcome-row').forEach(r=>{r.classList.remove('stake-fixed');const b=r.querySelector('.fix-stake-btn');b?.classList.remove('active');if(b)b.textContent='Fixar stake'});row.classList.add('stake-fixed');const b=row.querySelector('.fix-stake-btn');b?.classList.add('active');if(b)b.textContent='Stake fixa';}
function updateOutcomeRowUI(row){const type=row.dataset.betType||'back',btn=row.querySelector('.bet-toggle'),fb=row.querySelector('.out-freebet'),comOn=row.querySelector('.out-commission-enabled'),boostOn=row.querySelector('.out-boost-enabled');if(btn){btn.textContent=type==='lay'?'L':'B';btn.classList.toggle('lay',type==='lay');btn.classList.toggle('back',type!=='lay');btn.title=type==='lay'?'LAY — apostar contra':'BACK — apostar a favor'}if(fb?.checked&&type==='lay'){fb.checked=false}row.querySelector('.commission-percent')?.classList.toggle('show',!!comOn?.checked);row.querySelector('.boost-percent')?.classList.toggle('show',!!boostOn?.checked);const odd=parseNum(row.querySelector('.out-odd')?.value),boost=boostOn?.checked?Math.max(0,parseNum(row.querySelector('.out-boost')?.value)):0,eff=odd>1?odd*(1+boost/100):0,displayOdd=fb?.checked&&eff>1?eff-1:eff,el=row.querySelector('.effective-odd');if(el)el.textContent=displayOdd?displayOdd.toFixed(2).replace('.',','):'0,00';const stake=parseNum(row.querySelector('.out-stake')?.value),liab=row.querySelector('.lay-liability');if(liab)liab.textContent=type==='lay'&&eff>1?`Responsabilidade: ${brl((eff-1)*stake)}`:'';}
function applyHouseDefaults(row){const id=row.querySelector('.out-house').value;if(!id)return;const cfg=APP.settings.activeHouses?.[id]||{},com=row.querySelector('.out-commission'),boost=row.querySelector('.out-boost'),comOn=row.querySelector('.out-commission-enabled'),boostOn=row.querySelector('.out-boost-enabled');if(parseNum(cfg.commission)){com.value=parseNum(cfg.commission);comOn.checked=true}if(parseNum(cfg.boost)){boost.value=parseNum(cfg.boost);boostOn.checked=true}updateOutcomeRowUI(row);}
function gaussianSolve(A,b){const n=A.length,M=A.map((r,i)=>[...r,b[i]]);for(let col=0;col<n;col++){let pivot=col;for(let r=col+1;r<n;r++)if(Math.abs(M[r][col])>Math.abs(M[pivot][col]))pivot=r;if(Math.abs(M[pivot][col])<1e-10)return null;[M[col],M[pivot]]=[M[pivot],M[col]];const d=M[col][col];for(let c=col;c<=n;c++)M[col][c]/=d;for(let r=0;r<n;r++){if(r===col)continue;const f=M[r][col];for(let c=col;c<=n;c++)M[r][c]-=f*M[col][c];}}return M.map(r=>r[n]);}
function legFromRow(row,i){const odd=parseNum(row.querySelector('.out-odd').value),boostEnabled=row.querySelector('.out-boost-enabled').checked,boost=boostEnabled?Math.max(0,parseNum(row.querySelector('.out-boost').value)):0,commissionEnabled=row.querySelector('.out-commission-enabled').checked,commission=commissionEnabled?Math.min(100,Math.max(0,parseNum(row.querySelector('.out-commission').value)))/100:0,type=row.dataset.betType||'back',freebet=row.querySelector('.out-freebet').checked,stake=parseNum(row.querySelector('.out-stake').value),fixed=row.classList.contains('stake-fixed');return {i,target:i,house:row.querySelector('.out-house').value,label:`Resultado ${i+1}`,odd,boost,commission,type,freebet,stake,fixed,effectiveOdd:odd*(1+boost/100)};}
function unitPayoff(leg,outcome){const o=leg.effectiveOdd,c=leg.commission;if(leg.freebet)return outcome===leg.target?(o-1)*(1-c):0;if(leg.type==='lay')return outcome===leg.target?-(o-1):(1-c);return outcome===leg.target?(o-1)*(1-c):-1;}
function unitCost(leg){if(leg.freebet)return 0;return leg.type==='lay'?(leg.effectiveOdd-1):1;}
function resetSureDisplay(msg='Aguardando odds'){$('#arbMargin').textContent=$('#arbReturn').textContent=$('#arbProfit').textContent=$('#arbRoi').textContent='—';$('#impliedSum').textContent='—';$('#arbStatus').textContent=msg;$('#arbStatus').className='';$('#sureResult').className='calc-result neutral';$('#allocationBox').innerHTML='';}
function solveForTargets(legs,targets){const n=legs.length,work=legs.map((l,i)=>({...l,target:targets[i]}));let fixedIndex=work.findIndex(l=>l.fixed);const freeIndex=work.findIndex(l=>l.freebet);if(freeIndex>=0)fixedIndex=freeIndex;if(fixedIndex<0)fixedIndex=0;const fixedStake=work[fixedIndex].stake;if(fixedStake<=0)return null;const A=[],b=[];for(let out=1;out<n;out++){A.push(work.map(l=>unitPayoff(l,out)-unitPayoff(l,0)));b.push(0)}const fixedEq=Array(n).fill(0);fixedEq[fixedIndex]=1;A.push(fixedEq);b.push(fixedStake);const stakes=gaussianSolve(A,b);if(!stakes||stakes.some(x=>!Number.isFinite(x)||x<-.005))return null;const safeStakes=stakes.map(x=>Math.max(0,x));const profits=Array.from({length:n},(_,out)=>work.reduce((sum,l,i)=>sum+unitPayoff(l,out)*safeStakes[i],0));const profit=Math.min(...profits),maxProfit=Math.max(...profits),cashUsed=work.reduce((sum,l,i)=>sum+unitCost(l)*safeStakes[i],0),roi=cashUsed?profit/cashUsed*100:0,ret=cashUsed+profit;return {legs:work,stakes:safeStakes,profits,profit,maxProfit,cashUsed,roi,ret,margin:roi,isArb:profit>0.005,fixedIndex};}
function solveSimpleSure(legs){const n=legs.length;const layIdx=legs.map((l,i)=>l.type==='lay'?i:-1).filter(i=>i>=0);if(!layIdx.length)return solveForTargets(legs,legs.map((_,i)=>i));let best=null;const targets=legs.map((_,i)=>i);function search(k){if(k===layIdx.length){const r=solveForTargets(legs,targets);if(!r)return;const score=[r.profit,-Math.abs(r.maxProfit-r.profit),-r.cashUsed];const bestScore=best?[best.profit,-Math.abs(best.maxProfit-best.profit),-best.cashUsed]:null;if(!best||score[0]>bestScore[0]+1e-8||(Math.abs(score[0]-bestScore[0])<1e-8&&score[1]>bestScore[1]+1e-8)||(Math.abs(score[0]-bestScore[0])<1e-8&&Math.abs(score[1]-bestScore[1])<1e-8&&score[2]>bestScore[2]))best=r;return;}const idx=layIdx[k];for(let t=0;t<n;t++){targets[idx]=t;search(k+1)}targets[idx]=idx;}search(0);return best;}
function calcSure(){const rows=$$('.outcome-row'),legs=rows.map(legFromRow);if(legs.some(l=>l.odd<=1)){toast('Informe uma odd válida em todas as casas.');resetSureDisplay('Odds incompletas');return null}if(legs.filter(l=>l.freebet).length>1){toast('Use no máximo uma Freebet por cálculo.');return null}const free=legs.findIndex(l=>l.freebet);if(free>=0){if(legs[free].type==='lay'){toast('Freebet precisa ser BACK.');return null}setFixedRow(rows[free]);legs.forEach((l,i)=>l.fixed=i===free)}let fixed=legs.findIndex(l=>l.fixed);if(fixed<0){fixed=0;setFixedRow(rows[0]);legs[0].fixed=true}if(legs[fixed].stake<=0){toast('Informe o valor da stake fixa.');return null}const result=solveSimpleSure(legs);if(!result){toast('Essa combinação não pôde ser equilibrada. Confira as odds e o tipo Back/Lay.');resetSureDisplay('Combinação inválida');return null}result.stakes.forEach((v,i)=>{const inp=rows[i].querySelector('.out-stake');if(inp&&!rows[i].classList.contains('stake-fixed'))inp.value=v.toFixed(2);updateOutcomeRowUI(rows[i])});const strategy=legs.some(l=>l.freebet)?'Freebet + cobertura':legs.some(l=>l.type==='lay')?'Back / Lay':'Back / Back';$('#impliedSum').textContent=strategy;$('#arbMargin').textContent=pct(result.margin);$('#arbReturn').textContent=brl(result.ret);$('#arbProfit').textContent=brl(result.profit);$('#arbRoi').textContent=pct(result.roi);$('#arbStatus').textContent=result.isArb?'Surebet com lucro em todos os resultados':result.profit>=-.01?'Operação equilibrada':'Não é surebet: existe resultado negativo';$('#arbStatus').className=result.isArb?'positive':result.profit<-.01?'negative':'';$('#sureResult').className=`calc-result ${result.isArb?'good':'bad'}`;$('#allocationBox').innerHTML=result.legs.map((l,i)=>{const stake=result.stakes[i],liability=l.type==='lay'?(l.effectiveOdd-1)*stake:0;return `<div class="alloc-row"><span>Casa ${i+1} • ${l.type.toUpperCase()}${l.freebet?' • Freebet':''}<small class="alloc-meta">${esc(houseById(l.house)?.nome||`Casa ${i+1}`)} • odd ${l.effectiveOdd.toFixed(2)}</small></span><strong>${l.type==='lay'?`${brl(stake)} / resp. ${brl(liability)}`:brl(stake)}</strong></div>`}).join('')+result.profits.map((p,i)=>`<div class="alloc-row outcome-profit ${p>=0?'profit-ok':'profit-bad'}"><span>Lucro se der Resultado ${i+1}</span><strong>${brl(p)}</strong></div>`).join('')+`<div class="alloc-row total-allocation"><span>Caixa próprio exposto</span><strong>${brl(result.cashUsed)}</strong></div>`;return {...result,strategy};}
async function saveSure(){const c=calcSure();if(!c){return}if(!$('#sureEvent').value.trim()){toast('Informe qual é o evento antes de salvar.');return}const outcomes=c.legs.map((l,i)=>({...l,commission:l.commission*100,stake:c.stakes[i],liability:l.type==='lay'?(l.effectiveOdd-1)*c.stakes[i]:0}));await addEntry({id:uid(),type:'surebet',date:$('#sureDate').value||todayISO(),createdAt:new Date().toISOString(),event:$('#sureEvent').value.trim(),investment:c.cashUsed,profit:c.profit,roi:c.roi,returnValue:c.ret,strategy:c.strategy,marketOutcomes:c.legs.length,outcomes,offers:outcomes});toast('Surebet salva no histórico.');}
function renderSureTable(){const arr=APP.entries.filter(e=>e.type==='surebet').sort((a,b)=>b.date.localeCompare(a.date));$('#sureTableWrap').innerHTML=tableOrEmpty(arr,`<table class="data-table"><thead><tr><th>Data</th><th>Evento</th><th>Estratégia</th><th>Caixa</th><th>Lucro</th><th>ROI</th><th></th></tr></thead><tbody>${arr.map(e=>`<tr><td>${fmtDate(e.date)}</td><td>${esc(e.event)}</td><td>${esc(e.strategy||'Back')}</td><td>${brl(e.investment)}</td><td class="${moneyClass(e.profit)}">${brl(e.profit)}</td><td>${pct(e.roi)}</td><td class="row-actions"><button data-delete="${e.id}">Excluir</button></td></tr>`).join('')}</tbody></table>`);}
function calcSpins(){const count=parseNum($('#spinCount').value),value=parseNum($('#spinValue').value),before=parseNum($('#spinBefore').value),after=parseNum($('#spinAfter').value),nominal=count*value,profit=after-before,conversion=nominal?profit/nominal*100:0;$('#spinNominal').textContent=brl(nominal);$('#spinProfit').textContent=brl(profit);$('#spinProfit').className=moneyClass(profit);$('#spinConversion').textContent=pct(conversion);return{count,value,before,after,nominal,profit,conversion}}
async function saveSpin(){const c=calcSpins(); if(!$('#spinHouse').value){toast('Selecione a casa.');return} await addEntry({id:uid(),type:'spins',date:$('#spinDate').value||todayISO(),createdAt:new Date().toISOString(),house:$('#spinHouse').value,...c});toast('Giros grátis registrados.');}
function renderSpins(){const arr=APP.entries.filter(e=>e.type==='spins');setMoney('#spinTotal',arr.reduce((a,e)=>a+entryProfit(e),0));$('#spinCountTotal').textContent=arr.reduce((a,e)=>a+parseNum(e.count),0);$('#spinAvgConversion').textContent=pct(arr.length?arr.reduce((a,e)=>a+parseNum(e.conversion),0)/arr.length:0);const sorted=[...arr].sort((a,b)=>b.date.localeCompare(a.date));$('#spinTableWrap').innerHTML=tableOrEmpty(sorted,`<table class="data-table"><thead><tr><th>Data</th><th>Casa</th><th>Giros</th><th>Nominal</th><th>Lucro</th><th>Conversão</th><th></th></tr></thead><tbody>${sorted.map(e=>`<tr><td>${fmtDate(e.date)}</td><td>${esc(houseById(e.house)?.nome||e.house)}</td><td>${e.count||0}</td><td>${brl(e.nominal)}</td><td class="${moneyClass(e.profit)}">${brl(e.profit)}</td><td>${pct(e.conversion)}</td><td class="row-actions"><button data-delete="${e.id}">Excluir</button></td></tr>`).join('')}</tbody></table>`);}
function renderHouses(filter=''){const q=filter.toLowerCase().trim(),list=APP.houses.filter(h=>!q||h.nome.toLowerCase().includes(q)||h.dominio.toLowerCase().includes(q));$('#housesGrid').innerHTML=list.map(h=>{const cfg=APP.settings.activeHouses[h.id]||{active:false,balance:0,commission:0,boost:0};return `<div class="house-card ${cfg.active?'active':''}" data-house-card="${h.id}"><div class="house-card-head"><div class="house-id">${houseLogo(h)}<div><b>${esc(h.nome)}</b><small>${esc(h.dominio)}</small></div></div><button class="toggle ${cfg.active?'on':''}" data-toggle-house="${h.id}" aria-label="Ativar"></button></div>${cfg.active?`<div class="house-config-grid"><label>Saldo R$<input data-house-setting="balance" data-house-id="${h.id}" type="number" step="0.01" value="${parseNum(cfg.balance)}"></label><label>Comissão %<input data-house-setting="commission" data-house-id="${h.id}" type="number" min="0" max="100" step="0.01" value="${parseNum(cfg.commission)}"></label><label>Aumento %<input data-house-setting="boost" data-house-id="${h.id}" type="number" min="0" step="0.01" value="${parseNum(cfg.boost)}"></label></div>`:''}</div>`}).join('');}
async function toggleHouse(id){const cfg=APP.settings.activeHouses[id]||{active:false,balance:0,commission:0,boost:0};cfg.active=!cfg.active;APP.settings.activeHouses[id]=cfg;await saveSettings();renderAll();}
async function setAllHouses(active){APP.settings.activeHouses=APP.settings.activeHouses||{};APP.houses.forEach(h=>{const old=APP.settings.activeHouses[h.id]||{};APP.settings.activeHouses[h.id]={active,balance:parseNum(old.balance),commission:parseNum(old.commission),boost:parseNum(old.boost)}});await saveSettings();renderAll();toast(active?'Todas as casas foram selecionadas.':'Todas as casas foram desmarcadas.');}

function tableOrEmpty(arr,html){return arr.length?html:`<div class="empty-state">Nenhum registro encontrado.</div>`}
function fmtDate(s){return new Date(s+'T12:00:00').toLocaleDateString('pt-BR')}
function renderHistory(){let arr=[...APP.entries];const type=$('#historyType').value,mon=$('#historyMonth').value;if(type!=='all')arr=arr.filter(e=>e.type===type);if(mon)arr=arr.filter(e=>e.date.startsWith(mon));arr.sort((a,b)=>(b.date+b.createdAt).localeCompare(a.date+a.createdAt));$('#historyTableWrap').innerHTML=tableOrEmpty(arr,`<table class="data-table"><thead><tr><th>Data</th><th>Tipo</th><th>Descrição</th><th>Lucro</th><th></th></tr></thead><tbody>${arr.map(e=>`<tr><td>${fmtDate(e.date)}</td><td>${e.type==='surebet'?'Surebet':e.type==='spins'?'Giros grátis':'Manual'}</td><td>${esc(entryLabel(e))}</td><td class="${moneyClass(e.profit)}">${brl(e.profit)}</td><td class="row-actions"><button data-delete="${e.id}">Excluir</button></td></tr>`).join('')}</tbody></table>`);}
async function saveManual(ev){ev.preventDefault();const value=parseNum($('#manualValue').value);if(!value){toast('Informe um valor diferente de zero.');return}await addEntry({id:uid(),type:'manual',date:$('#manualDate').value||todayISO(),createdAt:new Date().toISOString(),house:$('#manualHouse').value,description:$('#manualDesc').value.trim()||'Ajuste manual',profit:value});$('#manualEntry').close();toast('Movimentação salva.');}

function renderReports(){const s=sums();setMoney('#repToday',s.today);setMoney('#repWeek',s.week);setMoney('#repMonth',s.month);setMoney('#repTotal',s.total);const byDay={};APP.entries.forEach(e=>byDay[e.date]=(byDay[e.date]||0)+entryProfit(e));const vals=Object.entries(byDay).sort((a,b)=>a[1]-b[1]);const best=vals.at(-1),worst=vals[0];const sure=APP.entries.filter(e=>e.type==='surebet').reduce((a,e)=>a+entryProfit(e),0),spins=APP.entries.filter(e=>e.type==='spins').reduce((a,e)=>a+entryProfit(e),0);$('#hallStats').innerHTML=`<div class="hall-row"><span>Lucro em surebets</span><strong class="${moneyClass(sure)}">${brl(sure)}</strong></div><div class="hall-row"><span>Lucro em giros grátis</span><strong class="${moneyClass(spins)}">${brl(spins)}</strong></div><div class="hall-row"><span>Melhor dia</span><strong>${best?`${fmtDate(best[0])} • ${brl(best[1])}`:'—'}</strong></div><div class="hall-row"><span>Pior dia</span><strong>${worst?`${fmtDate(worst[0])} • ${brl(worst[1])}`:'—'}</strong></div><div class="hall-row"><span>Total de registros</span><strong>${APP.entries.length}</strong></div>`;}
function exportExcel(){const sum=sums(),rows=[['RELATÓRIO SURECONTROL'],['Gerado em',new Date().toLocaleString('pt-BR')],[],['RESUMO'],['Hoje',sum.today],['Semana',sum.week],['Mês',sum.month],['Total',sum.total],[],['MOVIMENTAÇÕES'],['Data','Tipo','Descrição','Estratégia','Casas / Odds','Investimento / Caixa','Lucro','ROI']];[...APP.entries].sort((a,b)=>a.date.localeCompare(b.date)).forEach(e=>{const legs=(e.outcomes||[]).map(o=>`${houseById(o.house)?.nome||o.house||'-'} ${String(o.type||'back').toUpperCase()} @ ${Number(o.effectiveOdd||o.odd||0).toFixed(2)}${o.freebet?' FB':''}${o.commission?` C:${o.commission}%`:''}${o.boost?` A:${o.boost}%`:''}`).join(' | ');rows.push([fmtDate(e.date),e.type,entryLabel(e),e.strategy||'',legs,e.investment||'',e.profit||0,e.roi||'']);});rows.push([],['CASAS ATIVAS'],['Casa','Domínio','Saldo','Comissão padrão %','Aumento padrão %']);activeHouses().forEach(([id,cfg])=>{const h=houseById(id);rows.push([h?.nome||id,h?.dominio||'',parseNum(cfg.balance),parseNum(cfg.commission),parseNum(cfg.boost)])});const html=`<html><head><meta charset="UTF-8"><style>table{border-collapse:collapse}td{border:1px solid #bbb;padding:6px}tr:first-child td{font-weight:bold;font-size:16px}</style></head><body><table>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</table></body></html>`;downloadBlob(new Blob(['\ufeff',html],{type:'application/vnd.ms-excel'}),`surecontrol-${todayISO()}.xls`);toast('Planilha gerada.');}
function exportJSON(){downloadBlob(new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),entries:APP.entries,settings:APP.settings},null,2)],{type:'application/json'}),`surecontrol-backup-${todayISO()}.json`)}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportPDF(){const s=sums(),win=window.open('','_blank');const rows=[...APP.entries].sort((a,b)=>b.date.localeCompare(a.date)).map(e=>`<tr><td>${fmtDate(e.date)}</td><td>${esc(entryLabel(e))}</td><td>${e.type}</td><td style="text-align:right">${brl(e.profit)}</td></tr>`).join('');win.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Relatório SureControl</title><style>body{font-family:Arial,sans-serif;padding:34px;color:#181818}h1{margin-bottom:4px}.muted{color:#666}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:24px 0}.card{border:1px solid #ddd;border-radius:10px;padding:14px}.card span{font-size:11px;color:#666}.card b{display:block;font-size:18px;margin-top:6px}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #ddd;text-align:left;font-size:12px}th{background:#f4f4f4}@media print{button{display:none}}</style></head><body><h1>SureControl</h1><div class="muted">Relatório gerado em ${new Date().toLocaleString('pt-BR')}</div><div class="cards"><div class="card"><span>Hoje</span><b>${brl(s.today)}</b></div><div class="card"><span>Semana</span><b>${brl(s.week)}</b></div><div class="card"><span>Mês</span><b>${brl(s.month)}</b></div><div class="card"><span>Total</span><b>${brl(s.total)}</b></div></div><table><thead><tr><th>Data</th><th>Descrição</th><th>Tipo</th><th style="text-align:right">Lucro</th></tr></thead><tbody>${rows}</tbody></table><script>window.onload=()=>window.print()<\/script></body></html>`);win.document.close();}
async function importJSON(file){try{const data=JSON.parse(await file.text());if(!Array.isArray(data.entries))throw 0;for(const e of data.entries)await dbPut('entries',e);APP.entries=data.entries;if(data.settings){APP.settings=data.settings;await saveSettings()}renderAll();toast('Backup importado com sucesso.')}catch{toast('Arquivo de backup inválido.')}}

function renderSelectors(){const options=houseOptions();$('#spinHouse').innerHTML=options;$('#manualHouse').innerHTML=options;renderOutcomeRows();}
function renderAll(){renderDashboard();renderSureTable();renderSpins();renderHouses($('#houseSearch')?.value||'');renderHistory();renderReports();renderSelectors();}

function wire(){
  document.addEventListener('click',async e=>{
    const nav=e.target.closest('[data-nav]');if(nav){navigate(nav.dataset.nav);document.querySelectorAll('dialog[open]').forEach(d=>d.close());return}
    const open=e.target.closest('[data-open]');if(open){document.getElementById(open.dataset.open).showModal();return}
    const del=e.target.closest('[data-delete]');if(del&&confirm('Excluir este registro?')){await removeEntry(del.dataset.delete);return}
    const tog=e.target.closest('[data-toggle-house]');if(tog){await toggleHouse(tog.dataset.toggleHouse);return}
  });
  $('#houseCountOptions').addEventListener('click',e=>{const b=e.target.closest('[data-house-count]');if(b)setHouseCount(+b.dataset.houseCount);});
  $('#outcomeRows').addEventListener('click',e=>{const row=e.target.closest('.outcome-row');if(!row)return;const bet=e.target.closest('.bet-toggle');if(bet){toggleBetType(row);return}const fix=e.target.closest('.fix-stake-btn');if(fix){setFixedRow(row);resetSureDisplay();return}});
  $('#outcomeRows').addEventListener('change',e=>{const row=e.target.closest('.outcome-row');if(!row)return;if(e.target.matches('.out-house'))applyHouseDefaults(row);if(e.target.matches('.out-freebet,.out-commission-enabled,.out-boost-enabled')){if(e.target.matches('.out-freebet')&&e.target.checked)setFixedRow(row);updateOutcomeRowUI(row);}resetSureDisplay();});
  $('#outcomeRows').addEventListener('input',e=>{const row=e.target.closest('.outcome-row');if(row)updateOutcomeRowUI(row);});
  $('#calculateSure').addEventListener('click',calcSure);$('#saveSure').addEventListener('click',saveSure);
  ['spinCount','spinValue','spinBefore','spinAfter'].forEach(id=>$('#'+id).addEventListener('input',calcSpins));$('#saveSpin').addEventListener('click',saveSpin);
  $('#houseSearch').addEventListener('input',e=>renderHouses(e.target.value));
  $('#selectAllHouses').addEventListener('click',()=>setAllHouses(true));$('#clearAllHouses').addEventListener('click',()=>setAllHouses(false));
  $('#housesGrid').addEventListener('change',async e=>{if(e.target.matches('[data-house-setting]')){const id=e.target.dataset.houseId,key=e.target.dataset.houseSetting;APP.settings.activeHouses[id]=APP.settings.activeHouses[id]||{active:true,balance:0,commission:0,boost:0};APP.settings.activeHouses[id][key]=parseNum(e.target.value);await saveSettings();if(key==='balance')renderDashboard();renderSelectors();}});
  $('#historyType').addEventListener('change',renderHistory);$('#historyMonth').addEventListener('change',renderHistory);$('#saveManual').addEventListener('click',saveManual);$('#chartRange').addEventListener('change',drawChart);
  $('#themeToggle').addEventListener('click',toggleTheme);
  $('#exportExcel').addEventListener('click',exportExcel);$('#exportPdf').addEventListener('click',exportPDF);$('#exportJson').addEventListener('click',exportJSON);$('#backupBtn').addEventListener('click',exportJSON);$('#importJson').addEventListener('change',e=>e.target.files[0]&&importJSON(e.target.files[0]));
  window.addEventListener('resize',()=>{clearTimeout(window._chart);window._chart=setTimeout(drawChart,150)});
}

(async function init(){renderNav();$('#sureDate').value=$('#spinDate').value=$('#manualDate').value=todayISO();try{APP.houses=await fetch('casas.json').then(r=>r.json())}catch{document.body.innerHTML='<div style="padding:30px;color:white;font-family:system-ui"><h2>Não foi possível carregar casas.json</h2><p>Abra o projeto pelo Preview/servidor local do seu editor, e não diretamente como arquivo file://.</p></div>';return}await openDB();await loadData();let savedTheme=APP.settings.theme||'light';try{savedTheme=localStorage.getItem('surecontrol-theme')||savedTheme}catch{}applyTheme(savedTheme);wire();renderAll();})();
